check if any job passes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -52,6 +52,18 @@ version: 2.1
 
 commands:
 
+  save_exit_code:
+    description: Save status code to a file to be read later
+    parameters:
+      exit_code:
+        type: number
+        default: 0
+    steps:
+      - run:
+          name: Save exit code
+          command: |
+            echo <<parameters.exit_code>> > /tmp/exit_code
+
   setup:
     description: Checkout & Get name of target branch
     steps:
@@ -86,6 +98,8 @@ commands:
               echo "$CIRCLE_BRANCH" > /tmp/target_branch
 
             fi
+      - save_exit_code:
+          exit_code: 1
 
   check_is_pr:
     description: Check if the current build is happening because of a PR
@@ -149,6 +163,8 @@ commands:
           command: |
             ./ci/install_dependencies.sh
             python -m pip install toml
+
+
 jobs:
 
   lint:
@@ -174,6 +190,8 @@ jobs:
       - run:
           name: Build Staging
           command: ci/apply_sam_workflow_pr.sh staging
+      - save_exit_code:
+          exit_code: 0
 
   build_bastion:
     docker:
@@ -189,6 +207,8 @@ jobs:
       - run:
           name: Build Bastion
           command: ci/test_sam_workflow_pr.sh master
+      - save_exit_code:
+          exit_code: 0
 
   build_prod:
     docker:
@@ -204,6 +224,8 @@ jobs:
       - run:
           name: Build Prod
           command: ci/test_sam_workflow_pr.sh master
+      - save_exit_code:
+          exit_code: 0
 
   deploy_staging:
     docker:
@@ -219,6 +241,8 @@ jobs:
       - run:
           name: Deploy Staging
           command: ci/deploy.sh staging
+      - save_exit_code:
+          exit_code: 0
 
   deploy_bastion:
     docker:
@@ -234,6 +258,8 @@ jobs:
       - run:
           name: Deploy Bastion
           command: ci/deploy.sh bastion
+      - save_exit_code:
+          exit_code: 0
 
   deploy_prod:
     docker:
@@ -249,12 +275,39 @@ jobs:
       - run:
           name: Deploy Prod
           command: ci/deploy.sh prod
+      - save_exit_code:
+          exit_code: 0
+
+  determine_success_state:
+    docker:
+      - image: cimg/python:3.8
+    steps:
+      - run:
+          name: Wait until jobs are finished
+          command: |
+            while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" --header "Circle-Token: $CCI_TOKEN"| jq -r '.items[]|select(.name != "waiter")|.status' | grep -c "running") -gt 0 ]]
+              do
+                sleep 10
+              done
+      - run: echo "All required jobs have now completed"
+      - run:
+          name: Determine success
+          command: |
+            exit_status="$(cat /tmp/exit_status)"
+            if [[ "$exit_status" = 0 ]]
+            then
+              exit 0
+            else
+              exit 1
+            fi
+
 
 workflows:
     version: 2
     test-build-staging:
       jobs:
         - lint
+        - determine_success_state
             # filters:
             #   branches:
             #     only:
